### PR TITLE
Drop extra `f` wrapping the inner function

### PR DESCRIPTION
**Pull request by garyb**
@natefaubion pointed this out - it seems we never do anything useful with it internally, and it means we pay for another bind everywhere. /cc @jdegoes

### CODE REVIEW

**Comment by jdegoes** [comment]
I don't have any objection to this, but keep in mind they are _not equivalent_.

In the `f (a -> f b)` formulation, the creation of the function may entail an effect, and different values fed to the function may result in different types of effects. However, in the `f (a -> b)` formulation, the effect is already pre-determined and may not vary based on the value fed the function.

Clearly `f (a -> f b)` is the most general case, but does slow things down noticeably, so maybe worth specializing.

**Comment by natefaubion** [comment]
The `MealyT` constructor was not exported, so it wasn't actually possible to construct such a thing.

**Comment by jdegoes** [comment]
@natefaubion Well then, that makes it a no-brainer!

**Comment by garyb** [comment]
^ Yeah Nathan beat me to it.

> Well then, that makes it a no-brainer!

Ok, great :smile:

**Pull request merged**
